### ISSUE TITLE
Manage access for shiny-spoons-db / Package settings from  Gonick to Shiny-Spoons as admin

### ISSUE THREAD

**Issue by vishakha-verma** [scp756-221/term-project-shiny-spoons#16]
Team is facing an issue as permission_denied : wrote package

**Comment by vishakha-verma** [comment]
Hi Gonick,
Could you please add under manage access for all packages to Shiny-Spoons as admin, we are facing an issue as permission denied

**Comment by gonick** [comment]
Fixed!. Updated permissions in github packages
