### ISSUE TITLE
Dry run for integration of Grafana and Gatling

### ISSUE THREAD

**Issue by vishakha-verma** [scp756-221/term-project-shiny-spoons#26]
not all dashboards showing stats for new microservice S3

**Comment by vishakha-verma** [comment]
Hi Swaathi,
Could you please check we are getting stats in Garfana for S3, our new microservice in some of the dashboards and missing for some parts of dashboard

**Comment by vishakha-verma** [comment]
Can we please check grafana_flask_configmap.yaml and update it for S3 ( the new microservice)

**Comment by swaathis** [comment]
I'm testing Gattling with Grafana. The metrics for the third microservice haven't been added to the grafana_flask_configmap.yaml. I'll be adding the metrics of the third microservice s3 under k8s-dashoard.json.
