### ISSUE TITLE
testing kiali integration

### ISSUE THREAD

**Issue by vishakha-verma** [scp756-221/term-project-shiny-spoons#28]
not able to access the link

**Comment by vishakha-verma** [comment]
Hi Gonick,
We are not able to login to kiali URL generated, it asks for a token and the one provided doesn't work for us.

**Comment by vishakha-verma** [comment]
Hi Swaathi,
Can you please try this 

kubectl get secret -n istio-system $(kubectl get sa kiali-service-account -n istio-system -o "jsonpath={.secrets[0].name}") -o jsonpath={.data.token} | base64 -d

**Comment by swaathis** [comment]
Hi Vishaka,
I tried the command but the generated token is not logging into the Kiali dashboard. As per the Kiali documentation, the dashboard could be accessed anonymously (without a secret token). We might have to find some other way to get into the portal. There is a chance of missing yaml content for kiali. I'll check it out.

**Comment by smithakolan** [comment]
Start by checking on your Kiali instance/pod with:

$ kubectl -n istio-system describe po -l app=kiali
