### ISSUE TITLE
JSONDecodeError - while testing grafana dashboards

### ISSUE THREAD

**Issue by vishakha-verma** [scp756-221/term-project-shiny-spoons#29]

**Comment by swaathis** [comment]
The screenshot of JSONDecodeError while testing:
![JSON error](https://user-images.githubusercontent.com/97765662/162150427-92e3183c-ae71-41ad-b01d-0286eff78019.png)

**Comment by vishakha-verma** [comment]
The service has been redeployed and the error has been resolved
<img width="1440" alt="Screenshot 2022-04-10 at 10 35 46 PM" src="https://user-images.githubusercontent.com/65904510/162865366-79ecc86a-a67b-46de-baf5-eae768f77cbb.png">
.

**Comment by vishakha-verma** [comment]
issue has been resolved and we are good to close it.
