### ISSUE TITLE
Check load testing analytics of microservice on Grafana

### ISSUE THREAD

**Issue by smithakolan** [scp756-221/term-project-shiny-spoons#47]

**Comment by vishakha-verma** [comment]
Hi team,
Please find input from yesterday's call
<img width="1440" alt="Screenshot 2022-04-10 at 10 55 17 PM" src="https://user-images.githubusercontent.com/65904510/162864249-f8134d25-cb90-4b12-b6fe-9cced8c0c8fb.png">
.

**Comment by vishakha-verma** [comment]
@farhan-sfu @gonick can you please confirm if we are good to close this issue.

**Comment by farhan-sfu** [comment]
We are good to close
