### ISSUE TITLE
Simulate disruptions in microservice and observe results in Grafana dashboard

### ISSUE THREAD

**Issue by smithakolan** [scp756-221/term-project-shiny-spoons#48]

**Comment by vishakha-verma** [comment]
Hi Team,
Please find below inputs from yesterday's call
<img width="1440" alt="Screenshot 2022-04-10 at 10 47 28 PM" src="https://user-images.githubusercontent.com/65904510/162864044-e3d43398-f8f9-4732-ad33-cd2a64b0f3b6.png">
.

**Comment by vishakha-verma** [comment]
Also here are the results from Grafana
<img width="1440" alt="Screenshot 2022-04-10 at 11 03 47 PM 1" src="https://user-images.githubusercontent.com/65904510/162865983-5dd87295-fbc0-4065-bd79-67a3c3c4da7c.png">
